### PR TITLE
Hello-Microverse  Pull Request

### PR DESCRIPTION
**Pull request by Cosmosha**
Hello Microverse project pull request

### CODE REVIEW

**Review by GedeonTS — COMMENTED** [review]
# STATUS: CHANGES REQUIRED :recycle: :

Hi @Cosmosha , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights :tophat:  :+1: 
- No linter errors :+1: 
- Good use of .gitignore :+1: 
## Required Changes ♻️
- [ ] Kindly make sure you submit an open PR for review to respect Github flow :recycle: 
- [ ] Kindly add an edited README based on this [template](https://github.com/microverseinc/readme-template) provided by Microverse. :recycle: , as per the project requirements.
- [ ] It would be better to write a more descriptive PR summary and title to make your project look professional, describing all the steps you followed to complete this milestone.
_Check the comments under the review._

## Optional suggestions
- [ OPTIONAL ] :thinking: In my opinion, it would be better to write more descriptive commit messages in the future, starting with a capital letter, using imperative form, and above all describing clearly the change you made, in order to make your project professional
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Cosmosha** [comment]
Hi @GedeonTS ,
Thank you so much for reviewing my repo, the correction is noted.

**Comment by Cosmosha** [comment]
HI @GedeonTS , 
Please the required changes have been done. Can you kindly direct me on how  I can request for re-review without creating a new pull request as mentioned in your previous comment?

**Comment by GedeonTS** [comment]
Hi @Cosmosha , to submit for re-review, use the same link as for first review and paste it in the dashboard, just the way you did for the first time. 

But since you already merged you will have to create a new PR for this time

**Pull request merged**
